version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "5172:5172"
    depends_on:
      - backend
    restart: unless-stopped
